# Generated by Django 4.0.4 on 2022-09-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='image',
            field=models.ImageField(upload_to='develop/db_images'),
        ),
    ]
