# Generated by Django 4.0.4 on 2022-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0002_alter_floor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ManyToManyField(to='develop.room_type'),
        ),
    ]
