# Generated by Django 4.0.4 on 2022-11-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0003_room_type_room_room_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='brehova/4. patro/401.jpg', upload_to='develop/db_images'),
        ),
    ]
