# Generated by Django 4.0.4 on 2023-01-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0004_alter_floor_options_alter_room_options_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.TextField(default=''),
        ),
    ]
